// Academic Module - Custom Error Class
export class AcademicError extends Error {
    constructor(
        message: string,
        public code: string,
        public statusCode: number = 400
    ) {
        super(message);
        this.name = 'AcademicError';
    }
}

// Error codes for better debugging
export const ErrorCodes = {
    // Academic Year
    ACADEMIC_YEAR_NOT_FOUND: 'ACADEMIC_YEAR_NOT_FOUND',
    INVALID_DATE_RANGE: 'INVALID_DATE_RANGE',
    CANNOT_DELETE_CURRENT: 'CANNOT_DELETE_CURRENT',

    // Session Locking
    SESSION_LOCKED: 'SESSION_LOCKED',
    SESSION_ALREADY_LOCKED: 'SESSION_ALREADY_LOCKED',
    SESSION_NOT_LOCKED: 'SESSION_NOT_LOCKED',
    ATTENDANCE_LOCKED: 'ATTENDANCE_LOCKED',
    MARKS_LOCKED: 'MARKS_LOCKED',
    FEES_LOCKED: 'FEES_LOCKED',
    ENROLLMENT_LOCKED: 'ENROLLMENT_LOCKED',

    // Promotion
    PROMOTION_NOT_ALLOWED: 'PROMOTION_NOT_ALLOWED',
    NO_TARGET_CLASS: 'NO_TARGET_CLASS',
    ENROLLMENT_NOT_FOUND: 'ENROLLMENT_NOT_FOUND',
    STUDENT_ALREADY_PROMOTED: 'STUDENT_ALREADY_PROMOTED',

    // Class
    CLASS_NOT_FOUND: 'CLASS_NOT_FOUND',
    CLASS_DUPLICATE: 'CLASS_DUPLICATE',
    CLASS_HAS_SECTIONS: 'CLASS_HAS_SECTIONS',

    // Section
    SECTION_NOT_FOUND: 'SECTION_NOT_FOUND',
    SECTION_DUPLICATE: 'SECTION_DUPLICATE',

    // Subject
    SUBJECT_NOT_FOUND: 'SUBJECT_NOT_FOUND',
    SUBJECT_DUPLICATE: 'SUBJECT_DUPLICATE',
    SUBJECT_HAS_CHAPTERS: 'SUBJECT_HAS_CHAPTERS',
    SUBJECT_ALREADY_ASSIGNED: 'SUBJECT_ALREADY_ASSIGNED',

    // Chapter & Topic
    CHAPTER_NOT_FOUND: 'CHAPTER_NOT_FOUND',
    CHAPTER_HAS_TOPICS: 'CHAPTER_HAS_TOPICS',
    TOPIC_NOT_FOUND: 'TOPIC_NOT_FOUND',

    // Lesson Plan
    LESSON_PLAN_NOT_FOUND: 'LESSON_PLAN_NOT_FOUND',

    // Timetable
    TIMETABLE_NOT_FOUND: 'TIMETABLE_NOT_FOUND',
    TIMETABLE_CONFLICT: 'TIMETABLE_CONFLICT',
    TEACHER_CONFLICT: 'TEACHER_CONFLICT',
    SLOT_NOT_FOUND: 'SLOT_NOT_FOUND',

    // General
    TEACHER_NOT_FOUND: 'TEACHER_NOT_FOUND',
    ASSIGNMENT_NOT_FOUND: 'ASSIGNMENT_NOT_FOUND',
    VALIDATION_ERROR: 'VALIDATION_ERROR',
    INTERNAL_ERROR: 'INTERNAL_ERROR'
} as const;


